name: Deploy to Server

on:
  push:
    branches:
      - dev
    paths:
      - "frontend/**"
      - ".github/workflows/**"

jobs:
  deploy:
    environment: baiduYunServer
    runs-on: ubuntu-latest

    steps:

      # 1 checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2 install pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # 3 node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 4 install
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: frontend

      # 5 build
      - name: Build project
        run: pnpm run build
        working-directory: frontend

      # 6 deploy
      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}

          SOURCE: "frontend/dist"
          TARGET: "${{ secrets.TARGET_PATH }}/dist"

          SCRIPT_AFTER: |
            echo "🔧 Fixing permissions..."
            chmod -R 755 ${{ secrets.TARGET_PATH }}/dist

            echo "🔄 Reloading Nginx..."
            sudo systemctl reload nginx

            echo "✅ Deployment finished!"